package(default_visibility = [
    "//antlropt/test:__subpackages__",
    "//test/org/perses:__subpackages__",
])

filegroup(
    name = "antlr_grammars",
    srcs = glob(["*"]),
)

filegroup(
    name = "c_grammar",
    srcs = ["C.g4"],
)
