// Auto-generated by Perses AST.
// DO NOT MODIFY.
grammar pnf_test;

a
    : /* Epsilon. */
    | b c
    | d
    ;

b
    : b_3 kleene_star__b_1
    ;

kleene_star__b_1
    : b_2*
    ;

b_2
    : c d
    ;

b_3
    : d d
    | optional__b_4 d
    ;

optional__b_4
    : c?
    ;

c
    : 'c'
    ;

d
    : 'd'
    ;