load("@com_google_protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "spartree_proto",
    srcs = ["SparTreeMessage.proto"],
)

java_proto_library(
    name = "spartree_java_proto",
    deps = [
    ],
)
