load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "CommonAstTest",
    srcs = ["CommonAstTest.kt"],
    deps = [
        "//:guava",
        "//:truth",
        "//src/org/perses/util/ast",
    ],
)
