load("//src/org/perses:reduction.bzl", "reduce")

package(default_visibility = ["//test/org/perses:__subpackages__"])

filegroup(
    name = "creduce_example",
    srcs = [
        "r.sh",
        "t.c",
    ],
)
