/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_perses_fuzzer_coveragecollector_AFLCoverageCollector */

#ifndef _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector
#define _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector
#ifdef __cplusplus
extern "C" {
#endif
#undef org_perses_fuzzer_coveragecollector_AFLCoverageCollector_MAP_SIZE
#define org_perses_fuzzer_coveragecollector_AFLCoverageCollector_MAP_SIZE 65536L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_perses_fuzzer_coveragecollector_AFLCoverageCollector_SharedMemory */

#ifndef _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_SharedMemory
#define _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_SharedMemory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_perses_fuzzer_coveragecollector_AFLCoverageCollector_CoverageReport */

#ifndef _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_CoverageReport
#define _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_CoverageReport
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_perses_fuzzer_coveragecollector_AFLCoverageCollector_Companion */

#ifndef _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_Companion
#define _Included_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_perses_fuzzer_coveragecollector_AFLCoverageCollector_Companion
 * Method:    setupSharedMemory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_00024Companion_setupSharedMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_perses_fuzzer_coveragecollector_AFLCoverageCollector_Companion
 * Method:    getSharedMemory
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_00024Companion_getSharedMemory
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_perses_fuzzer_coveragecollector_AFLCoverageCollector_Companion
 * Method:    closeSharedMemory
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_perses_fuzzer_coveragecollector_AFLCoverageCollector_00024Companion_closeSharedMemory
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
