load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

kt_jvm_test(
    name = "TDTreeTest",
    srcs = [
        "TDTreeTest.kt",
    ],
    deps = [
        "//:truth",
        "//src/org/perses/antlr/atn/tdtree",
    ],
)
