load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

kt_jvm_test(
    name = "PPRDiffUtilsTest",
    srcs = ["PPRDiffUtilsTest.kt"],
    deps = [
        "//ppr/src/org/perses/ppr/diff:ppr_diff_utils",
        "//test/org/perses:test_util",
    ],
)
