package(default_visibility = ["//test/org/perses:__subpackages__"])

filegroup(
    name = "clang_testsuite",
    srcs = glob(["clang_testsuite/*.c"]),
)

filegroup(
    name = "gcc_testsuite",
    srcs = glob(["gcc_testsuite/*.c"]),
)
