load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "RawDefinitionTest",
    srcs = [
        "RawDefinitionTest.kt",
    ],
    deps = [
        "//:truth",
        "//src/org/perses/reduction/reducer/latra/language/io",
    ],
)
