java_library(
    name = "tree_dotifier",
    srcs = [
        "DotGraph.java",
        "TreeDotifier.java",
    ],
    deps = [
        "//src/org/perses/antlr:parse_tree_with_parser",
        "//src/org/perses/grammar:facade_factory",
        "//src/org/perses/grammar:grammar_facade",
        "//src/org/perses/program",
        "//src/org/perses/tree/spar",
        "//src/org/perses/util:shell",
        "@maven//:com_google_flogger_flogger",
        "@maven//:com_google_guava_guava",
        "@maven//:org_antlr_antlr4_runtime",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)
