java_library(
    name = "tree_dotifier",
    srcs = [
        "DotGraph.java",
        "TreeDotifier.java",
    ],
    deps = [
        "//:flogger",
        "//:guava",
        "//src/org/perses/antlr:parse_tree_with_parser",
        "//src/org/perses/grammar:facade_factory",
        "//src/org/perses/grammar:grammar_facade",
        "//src/org/perses/program",
        "//src/org/perses/spartree",
        "//src/org/perses/util:shell",
        "@maven//:org_antlr_antlr4_runtime",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)
