package(default_visibility = ["//kitten/test/org/perses:__subpackages__"])

filegroup(
    name = "fuzzer_test_data",
    srcs = glob([
        "coverage_collector_test/*",
        "different_lang_test/*",
        "file_generator_testset/*",
        "file_generator_testset2/*",
        "grammar_for_testing/*",
        "mutation_testset/*",
        "spar_tree_generator_testset/*",
    ]),
)
