// Auto-generated by Perses AST.
// DO NOT MODIFY.
grammar OrigC;

AUX_TOKEN__primaryExpression_1
    : '__builtin_va_arg'
    ;
AUX_TOKEN__primaryExpression_2
    : '__builtin_offsetof'
    ;
AUX_TOKEN__typeSpecifier_1
    : '__m128'
    ;
AUX_TOKEN__typeSpecifier_2
    : '__m128d'
    ;
AUX_TOKEN__typeSpecifier_3
    : '__m128i'
    ;
AUX_TOKEN__typeSpecifier_4
    : '__typeof__'
    ;
AUX_TOKEN__functionSpecifier_1
    : '__inline__'
    ;
AUX_TOKEN__functionSpecifier_2
    : '__stdcall'
    ;
AUX_TOKEN__functionSpecifier_3
    : '__declspec'
    ;
AUX_TOKEN__asmKeyword_1
    : 'asm'
    ;
AUX_TOKEN__asmKeyword_2
    : '__asm__'
    ;
AUX_TOKEN__asmKeyword_3
    : '__asm'
    ;
AUX_TOKEN__gccAttributeSpecifier_1
    : '__attribute__'
    ;
AUX_TOKEN__asmStatement_1
    : '__volatile__'
    ;
IncludeDirective
    : '#' 'include' (~[\n])*
    ;
Auto
    : 'auto'
    ;
Break
    : 'break'
    ;
Case
    : 'case'
    ;
Char
    : 'char'
    ;
Const
    : 'const'
    ;
Nonnull
    : '_Nonnull'
    ;
Nullable
    : '_Nullable'
    ;
Continue
    : 'continue'
    ;
Default
    : 'default'
    ;
Do
    : 'do'
    ;
Double
    : 'double'
    ;
Else
    : 'else'
    ;
Enum
    : 'enum'
    ;
Extern
    : 'extern'
    ;
Float
    : 'float'
    ;
For
    : 'for'
    ;
Goto
    : 'goto'
    ;
If
    : 'if'
    ;
Inline
    : 'inline'
    ;
Int
    : 'int'
    ;
Long
    : 'long'
    ;
Register
    : 'register'
    ;
Restrict
    : 'restrict'
    ;
Restrict_gcc
    : '__restrict__'
    ;
Restrict_gcc2
    : '__restrict'
    ;
Extension_gcc
    : '__extension__'
    ;
Return
    : 'return'
    ;
Short
    : 'short'
    ;
Signed
    : 'signed'
    ;
Sizeof
    : 'sizeof'
    ;
Static
    : 'static'
    ;
Struct
    : 'struct'
    ;
Switch
    : 'switch'
    ;
Typedef
    : 'typedef'
    ;
Union
    : 'union'
    ;
Unsigned
    : 'unsigned'
    ;
Void
    : 'void'
    ;
Volatile
    : 'volatile'
    ;
While
    : 'while'
    ;
Alignas
    : '_Alignas'
    ;
Alignof
    : '_Alignof'
    ;
Alignof_gcc
    : '__alignof__'
    ;
Atomic
    : '_Atomic'
    ;
Bool
    : '_Bool'
    ;
Complex
    : '_Complex'
    ;
Generic
    : '_Generic'
    ;
Imaginary
    : '_Imaginary'
    ;
Noreturn
    : '_Noreturn'
    ;
StaticAssert
    : '_Static_assert'
    ;
ThreadLocal
    : '_Thread_local'
    ;
LeftParen
    : '('
    ;
RightParen
    : ')'
    ;
LeftBracket
    : '['
    ;
RightBracket
    : ']'
    ;
LeftBrace
    : '{'
    ;
RightBrace
    : '}'
    ;
Less
    : '<'
    ;
LessEqual
    : '<='
    ;
Greater
    : '>'
    ;
GreaterEqual
    : '>='
    ;
LeftShift
    : '<<'
    ;
RightShift
    : '>>'
    ;
Plus
    : '+'
    ;
PlusPlus
    : '++'
    ;
Minus
    : '-'
    ;
MinusMinus
    : '--'
    ;
Star
    : '*'
    ;
Div
    : '/'
    ;
Mod
    : '%'
    ;
And
    : '&'
    ;
Or
    : '|'
    ;
AndAnd
    : '&&'
    ;
OrOr
    : '||'
    ;
Caret
    : '^'
    ;
Not
    : '!'
    ;
Tilde
    : '~'
    ;
Question
    : '?'
    ;
Colon
    : ':'
    ;
Semi
    : ';'
    ;
Comma
    : ','
    ;
Assign
    : '='
    ;
StarAssign
    : '*='
    ;
DivAssign
    : '/='
    ;
ModAssign
    : '%='
    ;
PlusAssign
    : '+='
    ;
MinusAssign
    : '-='
    ;
LeftShiftAssign
    : '<<='
    ;
RightShiftAssign
    : '>>='
    ;
AndAssign
    : '&='
    ;
XorAssign
    : '^='
    ;
OrAssign
    : '|='
    ;
Equal
    : '=='
    ;
NotEqual
    : '!='
    ;
Arrow
    : '->'
    ;
Dot
    : '.'
    ;
Ellipsis
    : '...'
    ;
Identifier
    : IdentifierNondigit (IdentifierNondigit | Digit)*
    ;
fragment IdentifierNondigit
    : Nondigit
    | UniversalCharacterName
    ;
fragment Nondigit
    : [a-zA-Z_]
    ;
fragment Digit
    : [0-9]
    ;
fragment UniversalCharacterName
    : '\\u' HexQuad
    | '\\U' HexQuad HexQuad
    ;
fragment HexQuad
    : HexadecimalDigit HexadecimalDigit HexadecimalDigit HexadecimalDigit
    ;
Constant
    : IntegerConstant
    | FloatingConstant
    | CharacterConstant
    ;
fragment IntegerConstant
    : DecimalConstant IntegerSuffix?
    | OctalConstant IntegerSuffix?
    | HexadecimalConstant IntegerSuffix?
    | BinaryConstant
    ;
fragment BinaryConstant
    : '0' [bB] [0-1]+
    ;
fragment DecimalConstant
    : NonzeroDigit Digit*
    ;
fragment OctalConstant
    : '0' OctalDigit*
    ;
fragment HexadecimalConstant
    : HexadecimalPrefix HexadecimalDigit+
    ;
fragment HexadecimalPrefix
    : '0' [xX]
    ;
fragment NonzeroDigit
    : [1-9]
    ;
fragment OctalDigit
    : [0-7]
    ;
fragment HexadecimalDigit
    : [0-9a-fA-F]
    ;
fragment IntegerSuffix
    : UnsignedSuffix LongSuffix?
    | UnsignedSuffix LongLongSuffix
    | LongSuffix UnsignedSuffix?
    | LongLongSuffix UnsignedSuffix?
    ;
fragment UnsignedSuffix
    : [uU]
    ;
fragment LongSuffix
    : [lL]
    ;
fragment LongLongSuffix
    : 'll'
    | 'LL'
    ;
fragment FloatingConstant
    : DecimalFloatingConstant
    | HexadecimalFloatingConstant
    ;
fragment DecimalFloatingConstant
    : FractionalConstant ExponentPart? FloatingSuffix?
    | DigitSequence ExponentPart FloatingSuffix?
    ;
fragment HexadecimalFloatingConstant
    : HexadecimalPrefix HexadecimalFractionalConstant BinaryExponentPart FloatingSuffix?
    | HexadecimalPrefix HexadecimalDigitSequence BinaryExponentPart FloatingSuffix?
    ;
fragment FractionalConstant
    : DigitSequence? '.' DigitSequence
    | DigitSequence '.'
    ;
fragment ExponentPart
    : 'e' Sign? DigitSequence
    | 'E' Sign? DigitSequence
    ;
fragment Sign
    : '+'
    | '-'
    ;
fragment DigitSequence
    : Digit+
    ;
fragment HexadecimalFractionalConstant
    : HexadecimalDigitSequence? '.' HexadecimalDigitSequence
    | HexadecimalDigitSequence '.'
    ;
fragment BinaryExponentPart
    : 'p' Sign? DigitSequence
    | 'P' Sign? DigitSequence
    ;
fragment HexadecimalDigitSequence
    : HexadecimalDigit+
    ;
fragment FloatingSuffix
    : 'f'
    | 'l'
    | 'F'
    | 'L'
    ;
fragment CharacterConstant
    : '\'' CCharSequence '\''
    | 'L\'' CCharSequence '\''
    | 'u\'' CCharSequence '\''
    | 'U\'' CCharSequence '\''
    ;
fragment CCharSequence
    : CChar+
    ;
fragment CChar
    : ~['\\\r\n]
    | EscapeSequence
    ;
fragment EscapeSequence
    : SimpleEscapeSequence
    | OctalEscapeSequence
    | HexadecimalEscapeSequence
    | UniversalCharacterName
    ;
fragment SimpleEscapeSequence
    : '\\' ['"?abfnrtv\\]
    ;
fragment OctalEscapeSequence
    : '\\' OctalDigit
    | '\\' OctalDigit OctalDigit
    | '\\' OctalDigit OctalDigit OctalDigit
    ;
fragment HexadecimalEscapeSequence
    : '\\x' HexadecimalDigit+
    ;
StringLiteral
    : EncodingPrefix? '"' SCharSequence? '"'
    ;
fragment EncodingPrefix
    : 'u8'
    | 'u'
    | 'U'
    | 'L'
    ;
fragment SCharSequence
    : SChar+
    ;
fragment SChar
    : ~["\\\r\n]
    | EscapeSequence
    | '\\\n'
    | '\\\r\n'
    ;
ComplexDefine
    : '#' Whitespace? 'define' (~[#])* -> skip

    ;
AsmBlock
    : 'asm' '{' (~[}])* '}' -> skip

    ;
LineAfterPreprocessing
    : '#line' Whitespace* (~[\r\n])* -> skip

    ;
LineDirective
    : '#' Whitespace? DecimalConstant Whitespace? StringLiteral (~[\r\n])* -> skip

    ;
PragmaDirective
    : '#' Whitespace? 'pragma' Whitespace (~[\r\n])* -> skip

    ;
Whitespace
    : [ \t]+ -> skip

    ;
Newline
    : ('\r' '\n'?
    | '\n')
 -> skip

    ;
BlockComment
    : '/*' .*? '*/' -> skip

    ;
LineComment
    : '//' (~[\r\n])* -> skip

    ;


primaryExpression
    : Identifier
    | Constant
    | StringLiteral+
    | LeftParen expression RightParen
    | genericSelection
    | Extension_gcc? LeftParen compoundStatement RightParen
    | AUX_TOKEN__primaryExpression_1 LeftParen unaryExpression Comma typeName RightParen
    | AUX_TOKEN__primaryExpression_2 LeftParen typeName Comma unaryExpression RightParen
    ;

genericSelection
    : Generic LeftParen assignmentExpression Comma genericAssocList RightParen
    ;

genericAssocList
    : genericAssociation
    | genericAssocList Comma genericAssociation
    ;

genericAssociation
    : typeName Colon assignmentExpression
    | Default Colon assignmentExpression
    ;

postfixExpression
    : primaryExpression
    | postfixExpression LeftBracket expression RightBracket
    | postfixExpression LeftParen argumentExpressionList? RightParen
    | postfixExpression Dot Identifier
    | postfixExpression Arrow Identifier
    | postfixExpression PlusPlus
    | postfixExpression MinusMinus
    | LeftParen typeName RightParen LeftBrace initializerList RightBrace
    | LeftParen typeName RightParen LeftBrace initializerList Comma RightBrace
    | Extension_gcc LeftParen typeName RightParen LeftBrace initializerList RightBrace
    | Extension_gcc LeftParen typeName RightParen LeftBrace initializerList Comma RightBrace
    ;

argumentExpressionList
    : assignmentExpression
    | argumentExpressionList Comma assignmentExpression
    ;

unaryExpression
    : postfixExpression
    | PlusPlus unaryExpression
    | MinusMinus unaryExpression
    | unaryOperator castExpression
    | Sizeof unaryExpression
    | Sizeof LeftParen typeName RightParen
    | (Alignof | Alignof_gcc) LeftParen (typeName | unaryExpression) RightParen
    | AndAnd Identifier
    ;

unaryOperator
    : And
    | Star
    | Plus
    | Minus
    | Tilde
    | Not
    ;

castExpression
    : unaryExpression
    | LeftParen typeName RightParen castExpression
    | Extension_gcc LeftParen typeName RightParen castExpression
    ;

multiplicativeExpression
    : castExpression
    | multiplicativeExpression Star castExpression
    | multiplicativeExpression Div castExpression
    | multiplicativeExpression Mod castExpression
    ;

additiveExpression
    : multiplicativeExpression
    | additiveExpression Plus multiplicativeExpression
    | additiveExpression Minus multiplicativeExpression
    ;

shiftExpression
    : additiveExpression
    | shiftExpression LeftShift additiveExpression
    | shiftExpression RightShift additiveExpression
    ;

relationalExpression
    : shiftExpression
    | relationalExpression Less shiftExpression
    | relationalExpression Greater shiftExpression
    | relationalExpression LessEqual shiftExpression
    | relationalExpression GreaterEqual shiftExpression
    ;

equalityExpression
    : relationalExpression
    | equalityExpression Equal relationalExpression
    | equalityExpression NotEqual relationalExpression
    ;

andExpression
    : equalityExpression
    | andExpression And equalityExpression
    ;

exclusiveOrExpression
    : andExpression
    | exclusiveOrExpression Caret andExpression
    ;

inclusiveOrExpression
    : exclusiveOrExpression
    | inclusiveOrExpression Or exclusiveOrExpression
    ;

logicalAndExpression
    : inclusiveOrExpression
    | logicalAndExpression AndAnd inclusiveOrExpression
    ;

logicalOrExpression
    : logicalAndExpression
    | logicalOrExpression OrOr logicalAndExpression
    ;

conditionalExpression
    : logicalOrExpression (Question expression Colon conditionalExpression)?
    ;

assignmentExpression
    : conditionalExpression
    | unaryExpression assignmentOperator assignmentExpression
    ;

assignmentOperator
    : Assign
    | StarAssign
    | DivAssign
    | ModAssign
    | PlusAssign
    | MinusAssign
    | LeftShiftAssign
    | RightShiftAssign
    | AndAssign
    | XorAssign
    | OrAssign
    ;

expression
    : assignmentExpression
    | expression Comma assignmentExpression
    ;

constantExpression
    : conditionalExpression
    ;

declaration
    : Extension_gcc? declarationSpecifiers initDeclaratorList? Semi
    | staticAssertDeclaration
    | asmStatement
    ;

declarationSpecifiers
    : declarationSpecifier+
    ;

declarationSpecifiers2
    : declarationSpecifier+
    ;

declarationSpecifier
    : storageClassSpecifier
    | typeSpecifierWithAttrList
    | typeQualifier
    | functionSpecifier
    | alignmentSpecifier
    ;

initDeclaratorList
    : initDeclarator
    | initDeclaratorList Comma initDeclarator
    ;

initDeclarator
    : declarator
    | declarator Assign initializer
    ;

storageClassSpecifier
    : Typedef
    | Extern
    | Static
    | ThreadLocal
    | Auto
    | Register
    ;

typeSpecifier
    : Void
    | Char
    | Short
    | Int
    | Long
    | Float
    | Double
    | Signed
    | Unsigned
    | Bool
    | Complex
    | AUX_TOKEN__typeSpecifier_1
    | AUX_TOKEN__typeSpecifier_2
    | AUX_TOKEN__typeSpecifier_3
    | Extension_gcc LeftParen (AUX_TOKEN__typeSpecifier_1 | AUX_TOKEN__typeSpecifier_2 | AUX_TOKEN__typeSpecifier_3) RightParen
    | atomicTypeSpecifier
    | structOrUnionSpecifier
    | enumSpecifier
    | typedefName
    | AUX_TOKEN__typeSpecifier_4 LeftParen constantExpression RightParen
    ;

typeSpecifierWithAttrList
    : typeSpecifier gccAttributeSpecifier?
    ;

structOrUnionSpecifier
    : structOrUnion Identifier? LeftBrace structDeclarationList RightBrace
    | structOrUnion Identifier
    ;

structOrUnion
    : Struct
    | Union
    ;

structDeclarationList
    : structDeclaration
    | structDeclarationList structDeclaration
    ;

structDeclaration
    : Extension_gcc? specifierQualifierList structDeclaratorList? Semi
    | staticAssertDeclaration
    ;

specifierQualifierList
    : typeSpecifierWithAttrList specifierQualifierList?
    | typeQualifier specifierQualifierList?
    ;

structDeclaratorList
    : structDeclarator
    | structDeclaratorList Comma structDeclarator
    ;

structDeclarator
    : declarator
    | declarator? Colon constantExpression
    ;

enumSpecifier
    : Enum Identifier? LeftBrace enumeratorList RightBrace
    | Enum Identifier? LeftBrace enumeratorList Comma RightBrace
    | Enum Identifier
    ;

enumeratorList
    : enumerator
    | enumeratorList Comma enumerator
    ;

enumerator
    : enumerationConstant
    | enumerationConstant Assign constantExpression
    ;

enumerationConstant
    : Identifier
    ;

atomicTypeSpecifier
    : Atomic LeftParen typeName RightParen
    ;

typeQualifier
    : Const
    | Restrict
    | Restrict_gcc
    | Restrict_gcc2
    | Volatile
    | Atomic
    | Nonnull
    | Nullable
    ;

functionSpecifier
    : Inline
    | Noreturn
    | AUX_TOKEN__functionSpecifier_1
    | AUX_TOKEN__functionSpecifier_2
    | gccAttributeSpecifier
    | AUX_TOKEN__functionSpecifier_3 LeftParen Identifier RightParen
    ;

alignmentSpecifier
    : Alignas LeftParen typeName RightParen
    | Alignas LeftParen constantExpression RightParen
    ;

declarator
    : pointer? directDeclarator gccDeclaratorExtension*
    ;

directDeclarator
    : Identifier
    | LeftParen gccAttributeSpecifier? declarator RightParen
    | directDeclarator LeftBracket typeQualifierList? assignmentExpression? RightBracket
    | directDeclarator LeftBracket Static typeQualifierList? assignmentExpression RightBracket
    | directDeclarator LeftBracket typeQualifierList Static assignmentExpression RightBracket
    | directDeclarator LeftBracket typeQualifierList? Star RightBracket
    | directDeclarator LeftParen parameterTypeList RightParen
    | directDeclarator LeftParen identifierList? RightParen
    ;

gccDeclaratorExtension
    : asmKeyword LeftParen StringLiteral+ RightParen
    | gccAttributeSpecifier
    ;

asmKeyword
    : AUX_TOKEN__asmKeyword_1
    | AUX_TOKEN__asmKeyword_2
    | AUX_TOKEN__asmKeyword_3
    ;

gccAttributeSpecifier
    : AUX_TOKEN__gccAttributeSpecifier_1 LeftParen LeftParen gccAttributeList RightParen RightParen
    ;

gccAttributeList
    : (gccAttribute (Comma gccAttribute)*)?
    ;

gccAttribute
    : (~(Comma | LeftParen | RightParen) (LeftParen argumentExpressionList? RightParen)?)?
    ;

nestedParenthesesBlock
    : (~(LeftParen | RightParen) | LeftParen nestedParenthesesBlock RightParen)*
    ;

pointer
    : Star typeQualifierList?
    | Star typeQualifierList? pointer
    | Caret typeQualifierList?
    | Caret typeQualifierList? pointer
    ;

typeQualifierList
    : (typeQualifier | gccAttributeSpecifier)+
    ;

parameterTypeList
    : parameterList
    | parameterList Comma Ellipsis
    ;

parameterList
    : parameterDeclaration
    | parameterList Comma parameterDeclaration
    ;

parameterDeclaration
    : declarationSpecifiers declarator
    | declarationSpecifiers2 abstractDeclarator?
    ;

identifierList
    : Identifier
    | identifierList Comma Identifier
    ;

typeName
    : specifierQualifierList abstractDeclarator?
    ;

abstractDeclarator
    : pointer
    | pointer? directAbstractDeclarator gccDeclaratorExtension*
    ;

directAbstractDeclarator
    : LeftParen abstractDeclarator RightParen gccDeclaratorExtension*
    | LeftBracket typeQualifierList? assignmentExpression? RightBracket
    | LeftBracket Static typeQualifierList? assignmentExpression RightBracket
    | LeftBracket typeQualifierList Static assignmentExpression RightBracket
    | LeftBracket Star RightBracket
    | LeftParen parameterTypeList? RightParen gccDeclaratorExtension*
    | directAbstractDeclarator LeftBracket typeQualifierList? assignmentExpression? RightBracket
    | directAbstractDeclarator LeftBracket Static typeQualifierList? assignmentExpression RightBracket
    | directAbstractDeclarator LeftBracket typeQualifierList Static assignmentExpression RightBracket
    | directAbstractDeclarator LeftBracket Star RightBracket
    | directAbstractDeclarator LeftParen parameterTypeList? RightParen gccDeclaratorExtension*
    ;

typedefName
    : Identifier
    ;

initializer
    : assignmentExpression
    | LeftBrace initializerList RightBrace
    | LeftBrace initializerList Comma RightBrace
    ;

initializerList
    : designation? initializer
    | initializerList Comma designation? initializer
    ;

designation
    : designatorList Assign
    ;

designatorList
    : designator
    | designatorList designator
    ;

designator
    : LeftBracket constantExpression RightBracket
    | Dot Identifier
    ;

staticAssertDeclaration
    : StaticAssert LeftParen constantExpression Comma StringLiteral+ RightParen Semi
    ;

statement
    : labeledStatement
    | compoundStatement
    | expressionStatement
    | selectionStatement
    | iterationStatement
    | jumpStatement
    | asmStatement
    ;

asmStatement
    : asmKeyword (Volatile | AUX_TOKEN__asmStatement_1)? LeftParen (logicalOrExpression (Comma logicalOrExpression)*)? (Colon (logicalOrExpression (Comma logicalOrExpression)*)?)* RightParen Semi
    ;

labeledStatement
    : Identifier Colon statement
    | Case constantExpression Colon statement
    | Default Colon statement
    ;

compoundStatement
    : LeftBrace blockItemList? RightBrace
    ;

blockItemList
    : blockItem
    | blockItemList blockItem
    ;

blockItem
    : declaration
    | statement
    ;

expressionStatement
    : expression? Semi
    ;

selectionStatement
    : If LeftParen expression RightParen statement (Else statement)?
    | Switch LeftParen expression RightParen statement
    ;

iterationStatement
    : While LeftParen expression RightParen statement
    | Do statement While LeftParen expression RightParen Semi
    | For LeftParen expression? Semi expression? Semi expression? RightParen statement
    | For LeftParen declaration expression? Semi expression? RightParen statement
    ;

jumpStatement
    : Goto Identifier Semi
    | Continue Semi
    | Break Semi
    | Return expression? Semi
    | Goto unaryExpression Semi
    ;

compilationUnit
    : translationUnit? EOF
    ;

translationUnit
    : externalDeclaration
    | translationUnit externalDeclaration
    ;

externalDeclaration
    : functionDefinition
    | declaration
    | IncludeDirective
    | Semi
    ;

functionDefinition
    : Extension_gcc? declarationSpecifiers? declarator declarationList? compoundStatement
    ;

declarationList
    : declaration
    | declarationList declaration
    ;

