load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "JarFileTest",
    srcs = [
        "JarFileTest.kt",
    ],
    test_class = "org.perses.util.java.JarFileTest",
    deps = [
        "//:truth",
        "//src/org/perses/util/java",
    ],
)
