package(default_visibility = [
    "//visibility:public",
])

filegroup(
    name = "files",
    srcs = [
        "afl_instrumented_binary",
        "test_input_1",
        "test_input_2",
        "test_input_3",
    ],
)
