package(default_visibility = ["//visibility:public"])

java_library(
    name = "enum_rule_type",
    srcs = [
        "RuleType.java",
    ],
    deps = [
        "@maven//:org_antlr_antlr4",
    ],
)
