package(default_visibility = ["//test/org/perses:__subpackages__"])

filegroup(
    name = "rust_testsuite",
    srcs = glob(["rust_testsuite/**/*.rs"],
                exclude = ["rust_testsuite/run-make-fulldeps/dep-info-spaces/*.rs"]),
)
