package org.perses.antlr.ast;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;

import java.io.PrintStream;
import java.util.Optional;
import java.util.function.Function;

public final class PersesGrammar extends AbstractPersesAst {

  public enum GrammarType {
    LEXER,

    PARSER,

    COMBINED;
  }

  private final GrammarType grammarType;
  private final String grammarName;
  private final PersesGrammarOptionsAst options;
  private final ImmutableList<AbstractPersesRuleDefAst> rules;
  private final SymbolTable symbolTable;
  private final ImmutableMap<RuleNameRegistry.RuleNameHandle, AbstractPersesRuleDefAst>
      ruleNameToRuleMap;

  public PersesGrammar(
      GrammarType grammarType,
      String grammarName,
      PersesGrammarOptionsAst options,
      ImmutableList<AbstractPersesRuleDefAst> rules,
      SymbolTable symbolTable) {
    this(
        grammarType,
        grammarName,
        options,
        rules,
        symbolTable,
        rules.stream()
            .collect(
                ImmutableMap.toImmutableMap(
                    AbstractPersesRuleDefAst::getRuleNameHandle, Function.identity())));
  }

  private PersesGrammar(
      GrammarType grammarType,
      String grammarName,
      PersesGrammarOptionsAst options,
      ImmutableList<AbstractPersesRuleDefAst> rules,
      SymbolTable symbolTable,
      ImmutableMap<RuleNameRegistry.RuleNameHandle, AbstractPersesRuleDefAst> ruleNameToRuleMap) {
    this.grammarType = grammarType;
    this.grammarName = grammarName;
    this.options = options;
    this.rules = rules;
    this.symbolTable = symbolTable;
    this.ruleNameToRuleMap = ruleNameToRuleMap;
  }

  public PersesGrammar copyWithNewName(String newGrammarName) {
    return new PersesGrammar(
        grammarType, newGrammarName, options, rules, symbolTable, ruleNameToRuleMap);
  }

  public PersesGrammarOptionsAst getOptions() {
    return options;
  }

  public String getGrammarName() {
    return grammarName;
  }

  public GrammarType getGrammarType() {
    return grammarType;
  }

  public SymbolTable getSymbolTable() {
    return symbolTable;
  }

  public ImmutableList<AbstractPersesRuleDefAst> getRules() {
    return rules;
  }

  public Optional<AbstractPersesRuleDefAst> getRuleDefinition(String ruleName) {
    Optional<RuleNameRegistry.RuleNameHandle> ruleNameHandle =
        symbolTable.getRuleNameRegistry().get(ruleName);
    if (ruleNameHandle.isPresent()) {
      return getRuleDefinition(ruleNameHandle.get());
    } else {
      return Optional.empty();
    }
  }

  public Optional<AbstractPersesRuleDefAst> getRuleDefinition(
      RuleNameRegistry.RuleNameHandle ruleNameHandle) {
    AbstractPersesRuleDefAst def = ruleNameToRuleMap.get(ruleNameHandle);
    return Optional.ofNullable(def);
  }

  public void toSourceCode(PrintStream stream, int indent, boolean multiLineMode) {
    stream.println("// Auto-generated by Perses AST.");
    stream.println("// DO NOT MODIFY.");

    switch (grammarType) {
      case LEXER:
        stream.print("lexer ");
        break;
      case PARSER:
        stream.print("parser ");
        break;
      case COMBINED:
        break;
      default:
        throw new RuntimeException("Unreachable.");
    }
    stream.printf("grammar %s;\n", grammarName);
    stream.println();

    options.toSourceCode(stream, /*indent=*/ 0, /*multiLineMode=*/ false);

    for (AbstractPersesRuleDefAst rule : rules) {
      rule.toSourceCode(stream, 0, true);
      stream.println();
    }
  }

  @Override
  public int getChildCount() {
    return rules.size();
  }

  @Override
  public AbstractPersesRuleDefAst getChild(int index) {
    return rules.get(index);
  }

  @Override
  protected String getExtraLabelForTreeStructurePrinting() {
    return super.getExtraLabelForTreeStructurePrinting() + " grammar_name=" + grammarName;
  }

  @Override
  public AstTag getTag() {
    return AstTag.GRAMMAR;
  }

  public boolean isEquivalent(PersesGrammar other) {
    if (!ruleNameToRuleMap.keySet().equals(other.ruleNameToRuleMap.keySet())) {
      return false;
    }
    for (RuleNameRegistry.RuleNameHandle ruleNameHandle : ruleNameToRuleMap.keySet()) {
      if (!ruleNameToRuleMap
          .get(ruleNameHandle)
          .getBody()
          .isEquivalent(other.ruleNameToRuleMap.get(ruleNameHandle).getBody())) {
        return false;
      }
    }
    return true;
  }
}
