load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "EnumShaAlgorithmTest",
    srcs = [
        "EnumShaAlgorithmTest.kt",
    ],
    deps = [
        "//:truth",
        "//src/org/perses/util/hashing",
    ],
)
