java_library(
    name = "level_reduction_speed_analysis",
    srcs = [
        "AbstractHddPerformanceAnalysis.java",
        "LabeledXYSeriesCollection.java",
        "LevelReductionSpeedAnalysis.java",
    ],
    deps = [
        "//:flogger",
        "//:guava",
        "//src/org/perses/listener:profile_event_interface",
        "@maven//:org_jfree_jfreechart",
    ],
)
