java_library(
    name = "level_reduction_speed_analysis",
    srcs = [
        "AbstractHddPerformanceAnalysis.java",
        "LabeledXYSeriesCollection.java",
        "LevelReductionSpeedAnalysis.java",
    ],
    deps = [
        "//src/org/perses:perses_exception",
        "//src/org/perses/listener:profile_event_interface",
        "@maven//:com_google_flogger_flogger",
        "@maven//:com_google_guava_guava",
        "@maven//:org_jfree_jfreechart",
    ],
)
