load("@rules_python//python:defs.bzl", "py_test")

package(default_visibility = ["//visibility:public"])

py_test(
    name = "make_jar_self_executable_test",
    srcs = ["make_jar_self_executable_test.py"],
    data = ["make_jar_self_executable.sh"],
)
