load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = [
    "//visibility:public",
])

kt_jvm_library(
    name = "ast",
    srcs = [
        "AbstractCommonAst.kt",
        "IPrecedence.kt",
        "Indent.kt",
    ],
    deps = [
    ],
)
